var names;
names = "Jhon Dhoe";
alert(names);
var names;
names = "15 years old";
alert(names);
var names;
names = "Certified Moblie Application Development";
alert(names);
var names;
names = "PIZZA \n PIZZ \n PIZ \n PI \n P";
alert(names);
var names;
names = "My email address is example @example.com";
alert(names);
var names;
names = "I am trying to learn from the book A smarter\n way to learn javascript";
alert(names);
document.write("Yah! I can write HTML content through JavaScript");
alert("▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬");
